### ISSUE TITLE
data types - decimal formatting options for numerical columns

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#189]

**Comment by Marc-Andre-Rivet** [comment]
First draft on what might be needed for a general purpose number formatting scheme:

- template (undefined | string) -- a default behavior to start from for all subsequent values
- digits padding (qte, character) -- default: (qte=0, char='0')
- decimals padding (qte, character) -- default (qte=0, char='0')
- prefix (null | string) -- default `null`
- suffix (null | string) -- default `null`
- digit (object)
  - group separator (null | string) -- default `space`
  - grouping (null | number | number[]) -- default `null`
- decimal (object)
  - group separator (null | string) -- default `space`
  - grouping (null | number | number[]) -- default `null`
  - separator (null | string) -- default `.`
- negative styling (null | string | object) -- default `null`
  - prefix (null | string)
  - suffix (null | string)
- base (number) -- default `10`

While most cultures have 3 digits or minimally constant digits grouping, some have variable grouping -- for example Hindi groups hundreds in 3s and higher values in 2s (e.g. 4 178 233 --> 41 78 233)

This does not take into consideration international standards that sometimes omit the grouping for 4 digits (e.g. even with 3 digits grouping 9999 instead of expected 9 999)

Some combinations could become presets/templates (e.g. financial, percentage, etc.)

**Comment by chriddyp** [comment]
For the API, one approach might be to piggyback off of something like pyformat's syntax (https://pyformat.info/). d3-format (https://github.com/d3/d3-format) is based off of this syntax as well and I believe plotly.js uses this.

**Comment by Marc-Andre-Rivet** [comment]
One thing I was wondering is if we're facing users from multiple end-user languages, how consistent / inconsistent an experience we can create if we use a platform-specific approach.

**Comment by Marc-Andre-Rivet** [comment]
On a tangent, the table API is fairly complex as-is -- she should strive to make the entry-point for as easy as possible. Maybe that means a few presets like percentages, monetary, etc. to cover the basic cases and a more powerful API for specific needs.

**Comment by alexcjohnson** [comment]
My gut reaction (as with a lot of things 😅) was to take plotly.js's behavior as a baseline and mimic it until we see a need for something else. But I'm not sure that's quite right here. For one, plotly.js's default formatting is based on the axis range, and works hard to adapt (mostly for the tick labels, but also for hover info) when you zoom in or out, even though the data itself doesn't change. So a rigid format isn't so great in plotly.js, whereas in a table you NEED a rigid format to be able to quickly scan a column. But also in plotly.js we necessarily have all the data we're showing info about, whereas in a table you're often showing only a subset of the full data set, or you want to standardize the format across many data sets.

So to me that argues for using `d3-format` - which as @chriddyp notes is already used in plotly.js and is mostly consistent with python's format specifiers - and augmenting it with some helpers for common situations. If we include a table-wide [`formatLocale`](https://github.com/d3/d3-format#formatLocale), I think `d3-format` covers everything you describe above with the exception of the 4-digit-number separator exception (which incidentally plotly.js [handles](https://github.com/plotly/plotly.js/blob/b03bb3b01a851e201ebf98341144ca11a414378d/src/plots/cartesian/layout_attributes.js#L520-L528) in its non-d3 formatting... oh well)

I know this goes against the grain of most of our dash features, but one thought would be to write the helpers in python, and have them just be functions like `dash_table.format.money(decimals=2, negative='(')` that would spit out a d3 format string. The advantages would be less API impact and helping users learn to construct these format strings, by inspecting the output of the functions.

**Comment by Marc-Andre-Rivet** [comment]
@alexcjohnson I like the suggestion of combining `d3-format` (along with the consistency with plotly.js) with helpers to make the entry-point easier. While the [py, R, ...] implementations will be duplicated, this is part of the table contract, not Dash per-say and I don't have an issue with that. This would provide better integration & flexibility than the magic values + config that I had in mind.

It seems that date formatting has a library of its own. 4.6kB + 9kB minified for both libraries seems like a very decent cost to pay. Guessing plotly.js must leverage that one as well and it would make most sense to use that one as well.

In this scenario, we would want each flavor to provide the same set of helpers, with some cross-tested sanity & all to keep everything aligned -- shouldn't need much more as d3-* does the heavy lifting.

For Python, would the helpers simply require an additional file inside the distribution package? e.g. dash_table/format.py to be accessible?

**Comment by alexcjohnson** [comment]
> It seems that date formatting has a library of its own. 4.6kB + 9kB minified for both libraries seems like a very decent cost to pay. Guessing plotly.js must leverage that one as well and it would make most sense to use that one as well.

Yes, date is separate, plotly.js uses d3 for both.

> For Python, would the helpers simply require an additional file inside the distribution package? e.g. dash_table/format.py to be accessible?

Right, that's what I had in mind. It's possible there will (eventually) be uses for this outside of table as well, so we could imagine making it part of `dash`, or even a completely separate package... but also, if we're comfortable that this is the approach we're going to take, we wouldn't need to implement the helpers right away, they could come in with a future PR.
