### ISSUE TITLE
support for fixed columns on safari on an iPad

### ISSUE THREAD

**Issue by vedulaabhi** [plotly/dash-table#259]
@chriddyp 
@Marc-Andre-Rivet 
The fixed columns functionality is not working on iPad. (Example: Portfolio table in ispace)
The problem with the functionality is that the headers are fixed but not the data columns as such. 
This problem is only with safari browser. 

Please let me know if you need any further information.

**Comment by Marc-Andre-Rivet** [comment]
@vedulaabhi I've tried this out on Mobile Safari 12 and confirm that I can reproduce the issue. Neither the columns or the rows are fixed.

Problem seems to be related to the use of ```position: sticky;``` for the fixed portions of the table.

**Comment by Marc-Andre-Rivet** [comment]
Testing notes

Browserstack redirects locahost to bs-local.com on mobile devices, in order for the dev-server to behave correctly add:

1. ```127.0.0.1 bs-local.com``` to /etc/hosts
2. ```--host bs-local.com``` to the build.watch script

**Comment by Marc-Andre-Rivet** [comment]
@vedulaabhi If you referring to this entry https://github.com/plotly/dash-table/issues/259#issuecomment-442883871, this is not an actual resolution, it's just a note to whoever (maybe myself) comes back to fix this so that they can setup their dev environment correctly in order to reproduce and fix this bug.

If you are referring to https://github.com/plotly/dash-table/issues/259#issuecomment-442883167, I don't have a resolution yet. Just the basics of what is causing the issue.

Sorry about the confusion.

**Comment by vedulaabhi** [comment]
@Marc
Hi, is there any update this issue?
