### ISSUE TITLE
possibility to change the texts "Previous" and "Next" in "pagination_settings" 

### ISSUE THREAD

**Issue by moisesbites** [plotly/dash-table#300]
Please, in the "pagination_settings", would be good the possibility to have two parameters to change the texts "Next" and "Previous", for localization in other languages. 

Thank you.

**Comment by r-chris** [comment]
I would like to offer support for this request. The latest release (`v4.0.0`) has however, removed the `pagination_settings` in favour of `page_action` among other new arguments.

I would suggest to simply use icons or symbols such as `<` and `>` instead of written text to avoid the localisation issue if that is acceptable?

**Comment by Marc-Andre-Rivet** [comment]
https://github.com/plotly/dash-table/pull/595 reworked the ui for pagination. Now using ‘<‘ and ‘>’ icons instead of text. Closing as fixed.
