### ISSUE TITLE
Column selection via checkbox and radio items

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#317]
Similarly to how row selection works

**Comment by chriddyp** [comment]
What this UI could look like:
![image](https://user-images.githubusercontent.com/1280389/60902626-ecbc9f00-a23d-11e9-9118-da06f6071ecc.png)

**Comment by Marc-Andre-Rivet** [comment]
Discussion notes: Add a `column_selectable` prop at the table level that is similar to `row_selectable` + add a nested prop to columns that has the same type as deletable and will toggle whether a specific column header is selectable or not.

**Comment by Marc-Andre-Rivet** [comment]
Based on the work on `hideable`, wondering what we want the exact behavior to be for multi-row / merged headers.

Thinking of the following props:

`columns.selectable`: boolean | boolean[] | 'first' | 'last'
like for the other similar props on columns

`column_selectable`: false | 'single' | 'multi'
at the table-level, like `row_selectable`

Like for `hideable` some combinations might be problematic or make more or less sense, but it is left to the user to use it carefully. At least, as a first implementation.

By defining the type of selection at the column-level, we force consistency across columns and don't get into what it means to 'multi' and 'single' select at the same time.

The default for both props would be `false`. The user needing to turn both on in order to select columns.

Interestingly this leads to 'single' potentially returning multiple columns in `selected_columns`.

Interactions with deletable and hideable props should be defined. What does it mean to select and than hide or remove a column? Should it be removed from the selection? If the other way around, the column would not have been present in the list.

**Comment by alexcjohnson** [comment]
All sounds right to me.

> Interestingly this leads to 'single' potentially returning multiple columns in `selected_columns`.

Correct, `'single'` is a statement about the UI, not necessarily about the resulting props - as long as `'single'` means only one *checkbox* can be checked at a time, it's fine if that results in multiple columns. That means `selected_columns` should always be an array even for `'single'`, which conveniently matches how we handle `selected_rows`, right?

> What does it mean to select and then hide or remove a column? Should it be removed from the selection?

Definitely deleting a column should remove it from the selection, otherwise you're selecting something that doesn't exist anymore and callbacks will break. But I'm not so sure about hidden columns disappearing from the selection. I could see the expectation go either way. The closest analog for row selection is filtering, and a row can be filtered out and remain selected, which implies that perhaps columns should too? 

The big challenge with hidden + selected columns is UI: how does a user know that some hidden things are selected, and how do they deselect them? We could always make another menu ala hide/show, though that seems pretty heavy for a fairly unusual case. And we don't have any corresponding feature for rows - a selected and filtered-out row is likewise impossible to know about and deselect. So I feel like to start we could just allow it without any protection, and come back to it later with a solution that would work for both rows and columns.

### when we come back to it later

One solution that comes to mind: if you have a hidden selection, a note pops up somewhere saying like:
> ⚠️ Hidden Selection

and if you click (or just hover?) on that, you're presented with one or two buttons, to deselect hidden rows and/or columns as applicable.

We could also add a prop like `allow_hidden_selections: false` that would allow users to choose the other behavior. Or even `allow_hidden_selections: true | false | 'rows' | 'columns'` for more granularity.

**Comment by Marc-Andre-Rivet** [comment]
> which conveniently matches how we handle selected_rows, right?

Yes. That's exactly how `selected_rows` is defined -- always an array.

> Definitely deleting a column should remove it from the selection

Agreed.

> ⚠️ Hidden Selection

Interesting.

Programatically I think rows are already well covered with `derived_viewport_selected_rows` and `derived_virtual_selected_rows`. Of course this does not really help with the UI 😄. A "global" checkbox in the `select` column, in the headers, when option is `multi`, might be a more natural option for the rows if we want to add a UI for it. But I digress.

The `Hidden Selection` button does address one use case: select a column, make it hidden, remove it from the selection. It does not however cover the case where columns A|B|C are merged, A is hidden, B|C are then selected, A is made visible again. Now B|C are selected but there might be no UI equivalent for it: There's no hidden selection and there's no checkbox or radio that matches (expect if for some reason multi-header was used to define the action's availability)

Maybe the selection could *always* operate on the set of all columns. e.g. B|C are visible (with A hidden) but part of merged A|B|C -- selecting B|C means that in code we are really selecting A|B|C.

- expose `derived_selected_visible_columns` with the columns from `selected_columns` that are *not* hidden
- with multi-select this does not prevent the user from selecting additional columns, with single-select a hidden selection will be cleared by a new selection valid in the UI.
- Our current algorithm for resolving merged columns grouping is forward-looking only and would require some changes in this scenario

With the above, we could in theory get away with not having a special toggle UI at all, at least for a first implementation.

> `allow_hidden_selections`

First reaction is to refrain supporting this in a first implementation. If we have a compelling API, maybe this becomes redundant. If not, we can always add it later with the right default to make it backward compatible.
