### ISSUE TITLE
Scroll bar mis-alignment bug reappearing in latest Dash-Table version

### ISSUE THREAD

**Issue by vedulaabhi** [plotly/dash-table#324]
@chriddyp @Marc-Andre-Rivet @anocella 

Hi,
The bug of scroll bar misalignment (#216 ) is appearing again in the latest Dash Table version. 
This is impacting any upgrade in the Dash-Table for our Apps (ispace). 
Can please provide an update if I am missing something?

Thanks in advance

**Comment by Marc-Andre-Rivet** [comment]
Tested in https://dash.plot.ly/datatable/sizing `Vertical Scrolling via Fixed Rows` I am seeing the old behaviour again when the scrollbars are always displayed.

![image](https://user-images.githubusercontent.com/8092993/50907984-b7520880-13f6-11e9-81d5-cb3b6482977c.png)

Running some tests to see when the problem reappeared.

**Comment by Marc-Andre-Rivet** [comment]
This is a regression caused by the virtualization work
https://github.com/plotly/dash-table/pull/253

Specifically this line prevents the rest of the fragment styles from being evaluated correctly if there is no virtualization. This should only be evaluated and used in the style *if* virtualization is enabled.

https://github.com/plotly/dash-table/blob/d79b505bad7db4cf2f2ec8e68d4656cf1921a405/src/dash-table/derived/table/fragmentStyles.ts#L27
