### ISSUE TITLE
Conditional formatting in for loop broken since upgrade to 0.3.7

### ISSUE THREAD

**Issue by philspbr** [plotly/dash-table#450]
The conditional formatting stopped working since upgrading to 0.3.7 when used in a for loop.
Below code used to work fine in previous versions:

```
[{
      'if': {'column_id': str(x), 'filter': '{} < num(0.9)'.format(x)},
      'background-color': '#9cd5ac'
    } for x in ['column1','column2']
  ]
```
I found out that the numbers expression needs to be changed from num(0.9) to just 0.9, otherwise it will throw an error: "unable to evaluate target: syntax tree is invalid"

When I remove the num(), the error is gone but the conditional formatting still does not work.
How do I have to adapt my code?

**Comment by philspbr** [comment]
I was able to fix it using f-strings which are available from Python 3.6 onwards.

**Comment by alexcjohnson** [comment]
Glad you fixed it! FWIW in addition to dropping `num(...)`, column IDs in filter strings need to be in `{...}` in v3.7. And since `{}` are special in `.format` you need to double them, plus the insertion point, resulting in 3 brackets in the final result!

`'{{{}}} < 0.9'.format(x)`
to make the desired:
`'{column1} < 0.9'`

**Comment by philspbr** [comment]
To add to your answer, the correct code for my example is:

`'if': {'column_id': str(x), 'filter': f'{{{x}}} < 0.9'}`
