### ISSUE TITLE
Boolean values not showing

### ISSUE THREAD

**Issue by moi90** [plotly/dash-table#539]
Like in the experimental version, cells with boolean values are empty, regardless of True or False.

https://github.com/plotly/dash-table-experiments/issues/10

**Comment by Marc-Andre-Rivet** [comment]
Notes for implementation:

This is caused by react inability to handle boolean values inside of jsx(tsx).

See current usage: https://github.com/plotly/dash-table/blob/master/src/dash-table/components/CellLabel/index.tsx#L27

By changing line 27 for something like:
```
            {typeof value === 'boolean' ?
                value.toString() :
                value
            }
```
we should be able to display the boolean under a string format.

Additionally, adding support for `PropTypes.bool` in the dropdown props seems to work as-is with the current dropdown implementation and should be folded in with the explicit `toString` fix.

One of the dropdown props: https://github.com/plotly/dash-table/blob/master/src/dash-table/dash/DataTable.js#L686

That said, the table does not have native `boolean` type support and the resolution of this issue would not add that support.

Add some tests for label / input (focused) / dropdown (focused) + updating as text or from dropdown.

**Comment by Marc-Andre-Rivet** [comment]
@moi90 Thanks for reporting this.

**Comment by moi90** [comment]
@Marc-Andre-Rivet Thanks for working on this issue!
