### ISSUE TITLE
Bug editing column names while columns are hidden

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash-table#576]
Causes hidden columns to be dropped entirely

**Comment by alexcjohnson** [comment]
also applies to deleting columns while some are hidden - but clearing seems OK. Might be some "interesting" edge cases though when merged columns are partially hidden...

**Comment by Marc-Andre-Rivet** [comment]
This is the only instance in which `visibleColumns` is used instead of `columns` for an operation on the columns.

https://github.com/plotly/dash-table/blob/master/src/dash-table/derived/header/content.tsx#L275
https://github.com/plotly/dash-table/blob/master/src/dash-table/utils/actions.js#L59

Causes invalid updates to `columns` and `data` fields.
