### ISSUE TITLE
quotes are required for filtering text entries with spaces in it

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#598]
Currently, you need to supply quotes around text when filtering. I think our default behavior should allow filtering strings without this as using quotes isn't discoverable.

![filtering with spaces](https://user-images.githubusercontent.com/1280389/65345233-9c8f8080-db8e-11e9-97ac-b7cf37683241.gif)

**Comment by chriddyp** [comment]
Relatedly, I don't understand why `PRODUCT3` returns _all_ of the results?

**Comment by Marc-Andre-Rivet** [comment]
The quotes being required is not a bug but working as intended.

Expected in `4.3.0`
- User enters `PRODUCT 3`
- The filter parsing to fail resulting in a `red` highlight on that cell
- No filter is applied

Should be possible to allow for a more permissive string selector for the single column case because the form of the filter is limited to few cases:
- `<unary>`
- `<relational> <value|expression>`
- `<value|expression>`
