### ISSUE TITLE
[BUG] Left-most column clipped / overflow hidden

### ISSUE THREAD

**Issue by wdoppenberg** [plotly/dash-table#680]
First of all thank you for the great work on Dash.

Since the 4.6.0 update all tables in my Dash app have their left-most column clipped. This doesn't seem to be an issue with the styling / sizing of the dash-table object. The image below describes it best:

![image](https://user-images.githubusercontent.com/19874123/72598444-1c94df80-3910-11ea-87f2-ef3e25e0b000.png)

Furthermore, if I inspect the element, the whole table does size correctly, yet only the left-most column cells overflow.

Thank you in advance!

**Comment by apiljic** [comment]
I have something similar but on the right side. In 4.5.1 it is fine. In 4.6.0 not.

**Comment by neal-shah** [comment]
Disabling the "margin-left" property on <div class="row row-1"> inside the datatable object seems to unclip the left side, trying to figure out a way to override this as a workaround:

<img width="613" alt="Screenshot 2020-01-22 at 10 43 07" src="https://user-images.githubusercontent.com/11790825/72887805-4ed58100-3d04-11ea-9e37-d2938e656012.png">

**Comment by sgsikuga** [comment]
Where do I find the bootstrap.css file you are talking about? I have the same issue

**Comment by dereklarson** [comment]
This issue is coming up for me still, certainly a bit annoying. I believe it's at least correlated to, if not caused by, a change in CSS from 4.5.1 to 4.6.0. When I revert from 4.7.0 to 4.5.1, I have to perform a browser refresh for the changes to take effect, which tells me it's likely the CSS.

The examples below are:
 - Working: dash-table==4.5.1
 - Clipped: dash-table>=4.6.0.  (tested both 4.6.0 and 4.7.0)
(Confirming what @apiljic posted above)

<img width="500" alt="Screen Shot 2020-05-27 at 12 53 05 PM" src="https://user-images.githubusercontent.com/7772604/82979652-2b0baa00-a01a-11ea-8058-210a5ee1145d.png">
<img width="500" alt="Screen Shot 2020-05-27 at 12 53 41 PM" src="https://user-images.githubusercontent.com/7772604/82979682-42e32e00-a01a-11ea-9227-48f9d48c92fb.png">

If I find out anything more as I poke around for a solution, I'll post an update here.
(And as a side note, I'd love an easier way to style the tables, such as inheriting parent properties or simpler dark theme support! :)

**Comment by dereklarson** [comment]
After digging deeper, it appears that there is a CSS class naming collision between the dash_table table row and that from Bootstrap's layout system. 

For example, in my case I'm using the layout system from dash bootstrap components (dbc.Row and dbc.Col) and [importing the GRID theme](https://github.com/facultyai/dash-bootstrap-components/blob/master/dash_bootstrap_components/themes.py) as an external stylesheet. This theme contains a `.row` CSS entry which includes the margin settings @neal-shah mentioned above. 

At the same time, the `div` for a dash_table row uses a class string of "row row-1", so it picks up that bootstrap grid system class and applies the negative margins. So as it stands, it looks like dash_table isn't compatible with bootstrap css.

**Comment by polymer940c** [comment]
> Disabling the `margin-left` property on `<div class="row row-1">` inside the datatable object seems to unclip the left side:
> 
> <img alt="Screenshot 2020-01-22 at 10 43 07" width="613" src="https://user-images.githubusercontent.com/11790825/72887805-4ed58100-3d04-11ea-9e37-d2938e656012.png">
> 
> In my bootstrap.css file, I added the following as a workaround:
> 
> ```
> .row .row-1 {
>     margin-left: 0px;
> }
> ```

if this is following bootstrap, the parent container is missing the `container` class
