### ISSUE TITLE
Table of images or thumbnails please ??

### ISSUE THREAD

**Issue by Nabilcobain** [plotly/dash-table#800]
I don't know if this is what you are looking for but I managed to put the images in a table (bootstrap component) through a workaround.
Through the following function I transformed them into thumbnails and then wrote them in html components.

```
def get_thumbnail(path):   
   i = Image.open(path)
   i.thumbnail((100, 100), Image.LANCZOS)
   buff = BytesIO()
   i.save(buff, format="PNG")
   encoded_image = base64.b64encode(buff.getvalue()).decode('UTF-8')
   return (html.Img(src='data:image/png;base64,{}'.format(encoded_image)))
```

At this point I put them in a column of a pandas dataframe in the layout.

```
html.Div([
        dbc.Table.from_dataframe(pandas_df, striped=True, bordered=True, hover=True, responsive="sm")
        ],
        style = {'margin-right':'90px','margin-left':'90px'})
```
This is the result:
![Cattura](https://user-images.githubusercontent.com/34246173/63509041-761ced80-c4db-11e9-96ef-ecb4135bcda5.PNG)

P.S.
```
import dash_html_components as html
import dash_bootstrap_components as dbc`
```

_Originally posted by @ricky1192 in https://github.com/plotly/dash-table/issues/383#issuecomment-523855054_

**Comment by Bytecat01** [comment]
Hi,
I am new to dash (and html). But is there an alternative way to embed local images into the dash data_table instead of using dash_bootstrap_components? (I am running it locally). Unfortunately, my anaconda does not have access to this package. I can export my pandas dataframe as an HTML file, and the images appear via the <img> tags in the cells perfectly. 
What I tried was:
- Straight import into a dash table. The path shows up instead of the image;
- Tried using HTML.Table to create the table that way. Same result as the above.
- I can embed images via app.layout = html.Div(html.Img(src=app.get_asset_url("file.png"))) (by adding the assets folder). However this is for one off images, rather than a data table.

Has there been any movement on this functionality?
